**Realizado por:** Rodolfo Jesús Cruz Rebollar

**Matrícula:** A01368326

**Grupo:** 101

### Problem Statement
You are a data scientist working for a school

You are asked to predict the GPA of the current students based on the following provided data: 

 0   StudentID  int64  
 1   Age    int64  
 2   Gender int64  
 3   Ethnicity  int64  
 4   ParentalEducation  int64  
 5   StudyTimeWeekly    float64
 6   Absences   int64  
 7   Tutoring   int64  
 8   ParentalSupport    int64  
 9   Extracurricular    int64  
 10  Sports int64  
 11  Music  int64  
 12  Volunteering   int64  
 13  GPA    float64
 14  GradeClass float64

The GPA is the Grade Point Average, typically ranges from 0.0 to 4.0 in most educational systems, with 4.0 representing an 'A' or excellent performance.

The minimum passing GPA can vary by institution, but it's often around 2.0. This usually corresponds to a 'C' grade, which is considered satisfactory.

You need to create a Deep Learning model capable to predict the GPA of a Student based on a set of provided features.
The data provided represents 2,392 students.

In this excersice you will be requested to create a total of three models and select the most performant one.


### 1) Import Libraries

First let's import the following libraries, if there is any library that you need and is not in the list bellow feel free to include it

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

c:\Users\Rodolfo\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


### 2) Load Data

In [2]:
data = pd.read_csv("Student_performance_data _.csv")
data

StudentID  Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  \
0          1001   17       1          0                  2        19.833723   
1          1002   18       0          0                  1        15.408756   
2          1003   15       0          2                  3         4.210570   
3          1004   17       1          0                  3        10.028829   
4          1005   17       1          0                  2         4.672495   
...         ...  ...     ...        ...                ...              ...   
2387       3388   18       1          0                  3        10.680555   
2388       3389   17       0          0                  1         7.583217   
2389       3390   16       1          0                  2         6.805500   
2390       3391   16       1          1                  0        12.416653   
2391       3392   16       1          0                  2        17.819907   

      Absences  Tutoring  ParentalSupport  Extracurricular  Sports  Music  \
0            7         1                2                0       0      1   
1            0         0                1                0       0      0   
2           26         0                2                0       0      0   
3           14         0                3                1       0      0   
4           17         1                3                0       0      0   
...        ...       ...              ...              ...     ...    ...   
2387         2         0                4                1       0      0   
2388         4         1                4                0       1      0   
2389        20         0                2                0       0      0   
2390        17         0                2                0       1      1   
2391        13         0                2                0       0      0   

      Volunteering       GPA  GradeClass  
0                0  2.929196         2.0  
1                0  3.042915         1.0  
2                0  0.112602         4.0  
3                0  2.054218         3.0  
4                0  1.288061         4.0  
...            ...       ...         ...  
2387             0  3.455509         0.0  
2388             0  3.279150         4.0  
2389             1  1.142333         2.0  
2390             0  1.803297         1.0  
2391             1  2.140014         1.0  

[2392 rows x 15 columns]

### 3) Review you data:

Make sure you review your data.
Place special attention of null or empty values.

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   StudentID          2392 non-null   int64  
 1   Age                2392 non-null   int64  
 2   Gender             2392 non-null   int64  
 3   Ethnicity          2392 non-null   int64  
 4   ParentalEducation  2392 non-null   int64  
 5   StudyTimeWeekly    2392 non-null   float64
 6   Absences           2392 non-null   int64  
 7   Tutoring           2392 non-null   int64  
 8   ParentalSupport    2392 non-null   int64  
 9   Extracurricular    2392 non-null   int64  
 10  Sports             2392 non-null   int64  
 11  Music              2392 non-null   int64  
 12  Volunteering       2392 non-null   int64  
 13  GPA                2392 non-null   float64
 14  GradeClass         2392 non-null   float64
dtypes: float64(3), int64(12)
memory usage: 280.4 KB


### 4. Remove the columns not needed for Student performance prediction

- Choose only the columns you consider to be valuable for your model training.
- For example, StudentID might not be a good feature for your model, and thus should be removed from your main dataset, which other columns should also be removed?
- You can name that final dataset as 'dataset'

In [4]:
"""Columnas relevantes a seleccionar: Age, ParentalEducation, StudyTimeWeekly, Absenses, 
   ParentalSupport, Sports, GradeClass, GPA"""

dataset = data.iloc[:, [1, 4, 5, 6, 8, 10, 14, 13]]

dataset.head()

Age  ParentalEducation  StudyTimeWeekly  Absences  ParentalSupport  Sports  \
0   17                  2        19.833723         7                2       0   
1   18                  1        15.408756         0                1       0   
2   15                  3         4.210570        26                2       0   
3   17                  3        10.028829        14                3       0   
4   17                  2         4.672495        17                3       0   

   GradeClass       GPA  
0         2.0  2.929196  
1         1.0  3.042915  
2         4.0  0.112602  
3         3.0  2.054218  
4         4.0  1.288061

### 5. Check if the columns has any null values:
- Here you now have your final dataset to use in your model training.
- Before moving foward review your data check for any null or empty value that might be needed to be removed

In [5]:
# Revisar si existen valores nulos o faltantes en cada columna del dataset

dataset.isna().any()

Age                  False
ParentalEducation    False
StudyTimeWeekly      False
Absences             False
ParentalSupport      False
Sports               False
GradeClass           False
GPA                  False
dtype: bool

### 6. Prepare your data for training and for testing set:
 - First create a dataset named X, with all columns but GPA. These are the features
 - Next create another dataset named y, with only GPA column. This is the label
 - If you go to your Imports, you will see the following import: **'from sklearn.model_selection import train_test_split'**
 - Use that *train_test_split* function to create: X_train, X_test, y_train and y_test respectively. Use X and y datasets as parameters. Other parameters to use are: Test Size = 0.2, Random State = 42.
 
 - Standarize your features (X_train and X_test) by using the StandardScaler (investigate how to use fit_transform and transform functions). This will help the training process by dealing with normilized data.

 Note: Your X_train shape should be around (1913, 10). This means the dataset has 10 columns which should be the input.

In [6]:
# Dataset solo con variables predictoras sin la variable respuesta GPA

X = dataset.iloc[:, :7]

# Dataset solo con la variable respuesta GPA

y = dataset["GPA"]

# Crear conjuntos de entrenamiento y prueba para X, y

# Destinar 20% de los datos para probar el modelo y el 80% sobrante para entrenarlo

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

# Estandarizar/normalizar los valores de las variables sin considerar a la variable respuesta (GPA)

scaler = StandardScaler()

std_features = scaler.fit_transform(X_train, X_test)

std_features

array([[ 1.37285117,  2.26211643,  1.46815853, ..., -1.9146563 ,
         1.51039849,  0.82018081],
       [-0.40585814,  0.23853507, -1.27677348, ..., -1.02021491,
        -0.66207693,  0.82018081],
       [ 0.48349652,  1.25032575, -1.10363153, ..., -1.9146563 ,
        -0.66207693,  0.82018081],
       ...,
       [-0.40585814,  0.23853507, -1.08325424, ..., -0.12577352,
         1.51039849,  0.01141489],
       [ 1.37285117,  0.23853507, -0.93767144, ...,  0.76866788,
        -0.66207693,  0.82018081],
       [ 1.37285117,  0.23853507, -0.7578795 , ..., -0.12577352,
        -0.66207693,  0.82018081]])

### 7. Different Neural Network Architectures

**Nota:** se utilizará un valor de dropout igual a 0.5 para los modelos 3 y 4. 

#### Experiment 1: A single Dense Hidden Layer

In [7]:
# Experiment 1: a single dense hidden layer

E1 = Sequential()

# Agregar capa de entrada con 64 unidades y activación Relu y dimensión de entrada = 7

E1.add(Dense(64, activation="relu", input_dim = 7))

# Agregar capa densa oculta simple on 32 unidades y función de activación Relu

E1.add(Dense(32, activation="relu")) # single dense hidden layer

# Añadir capa de salida con 1 unidad 

E1.add(Dense(1))

c:\Users\Rodolfo\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [8]:
# Compilación del modelo 1

E1.compile(optimizer="adam", loss="mse", metrics=["mae"])

In [9]:
# Entrenamiento del modelo 1

E1.fit(X_train, y_train, epochs=100, batch_size=10, validation_split=0.2)

Epoch 1/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1.4415 - mae: 0.7374 - val_loss: 0.1245 - val_mae: 0.2772
Epoch 2/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1208 - mae: 0.2763 - val_loss: 0.1206 - val_mae: 0.2810
Epoch 3/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1037 - mae: 0.2628 - val_loss: 0.1306 - val_mae: 0.2953
Epoch 4/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1067 - mae: 0.2661 - val_loss: 0.1083 - val_mae: 0.2636
Epoch 5/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1097 - mae: 0.2660 - val_loss: 0.1131 - val_mae: 0.2734
Epoch 6/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0986 - mae: 0.2502 - val_loss: 0.0924 - val_mae: 0.2438
Epoch 7/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0929 - mae: 0.2446 - val_loss: 0.1059 - val_mae: 0.2624
Epoch 8/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0942 - mae: 0.2486 - val_loss: 0.0959 - val_mae: 0.2505
Epoch 9/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/

In [26]:
# Evaluar el modelo 1

eval1 = E1.evaluate(X_test, y_test)

print(f'Valores de pérdida modelo 1: {eval1}')

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0587 - mae: 0.1782 
Valores de pérdida modelo 1: [0.05687776580452919, 0.1798904687166214]


#### Experiment 2: A set of three Dense Hidden Layers

In [11]:
# Experiment 2: a single dense hidden layer

E2 = Sequential()

# Agregar capa de entrada con 64 unidades y activación Relu y dimensión de entrada = 7

E2.add(Dense(64, activation="relu", input_dim = 7))

# Agregar capa densa oculta 1 con 32 unidades y función de activación Relu

E2.add(Dense(32, activation="relu")) # dense hidden layer 1

# Agregar capa densa oculta 2 con 16 unidades y función de activación Relu

E2.add(Dense(16, activation="relu")) # dense hidden layer 2

# Agregar capa densa oculta 3 con 8 unidades y función de activación Relu

E2.add(Dense(8, activation="relu")) # dense hidden layer 3

# Añadir capa de salida con 1 unidad 

E2.add(Dense(1))

In [12]:
# Compilación del modelo 2 (con 3 capas densas ocultas)

E2.compile(optimizer = "adam", loss = "mse", metrics = ["mae"])

In [13]:
# Entrenamiento del modelo 2 

E2.fit(X_train, y_train, epochs=100, batch_size=10, validation_split=0.2)

Epoch 1/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 1.0956 - mae: 0.6838 - val_loss: 0.1627 - val_mae: 0.3234
Epoch 2/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1252 - mae: 0.2833 - val_loss: 0.1401 - val_mae: 0.3048
Epoch 3/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0974 - mae: 0.2575 - val_loss: 0.1196 - val_mae: 0.2815
Epoch 4/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0999 - mae: 0.2539 - val_loss: 0.1139 - val_mae: 0.2712
Epoch 5/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0912 - mae: 0.2432 - val_loss: 0.1526 - val_mae: 0.3190
Epoch 6/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1055 - mae: 0.2603 - val_loss: 0.1051 - val_mae: 0.2596
Epoch 7/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0904 - mae: 0.2425 - val_loss: 0.0917 - val_mae: 0.2423
Epoch 8/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0874 - mae: 0.2375 - val_loss: 0.1007 - val_mae: 0.2557
Epoch 9/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/

In [14]:
# Evaluar el modelo 2

eval2 = E2.evaluate(X_test, y_test)

print(f'Valores de pérdida modelo 2: {eval2}')

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0534 - mae: 0.1711 
Valores de pérdida modelo 2: [0.05030996352434158, 0.16920119524002075]


#### Experiment 3: Add a dropout layer after each Dense Hidden Layer

In [15]:
# Experiment 3: a single dense hidden layer

E3 = Sequential()

# Agregar capa de entrada con 64 unidades y activación Relu y dimensión de entrada = 7

E3.add(Dense(64, activation="relu", input_dim = 7))

# Agregar capa densa oculta 1 con 32 unidades y función de activación Relu

E3.add(Dense(32, activation="relu")) # dense hidden layer 1

# Agregar una capa de dropout después del dense hidden layer 1

E3.add(Dropout(0.5)) # dropout layer after dense hidden layer 1

# Agregar capa densa oculta 2 con 16 unidades y función de activación Relu

E3.add(Dense(16, activation="relu")) # dense hidden layer 2

# Agregar capa de dropout después del dense hidden layer 2

E3.add(Dropout(0.5)) # dropout layer after dense hidden layer 2

# Agregar capa densa oculta 3 con 8 unidades y función de activación Relu

E3.add(Dense(8, activation="relu")) # dense hidden layer 3

# Agregar capa de dropout después del dense hidden layer 3

E3.add(Dropout(0.5)) # dropout layer after dense hidden layer 3

# Añadir capa de salida con 1 unidad 

E3.add(Dense(1))

In [16]:
# Compilación del modelo 3 (con dropout layer después de cada hidden layer)

E3.compile(optimizer="adam", loss="mse", metrics=["mae"])

In [17]:
# Entrenamiento del modelo 3

E3.fit(X_train, y_train, epochs=100, batch_size=10, validation_split=0.2)

Epoch 1/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 17.4613 - mae: 3.0271 - val_loss: 2.7426 - val_mae: 1.4520
Epoch 2/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.0943 - mae: 1.4541 - val_loss: 1.8519 - val_mae: 1.1751
Epoch 3/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.1910 - mae: 1.1876 - val_loss: 1.3071 - val_mae: 0.9670
Epoch 4/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.6676 - mae: 1.0221 - val_loss: 1.0046 - val_mae: 0.8487
Epoch 5/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.4910 - mae: 0.9591 - val_loss: 0.8829 - val_mae: 0.7992
Epoch 6/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1649 - mae: 0.8479 - val_loss: 0.9469 - val_mae: 0.8215
Epoch 7/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1817 - mae: 0.8428 - val_loss: 0.8188 - val_mae: 0.7659
Epoch 8/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1083 - mae: 0.8395 - val_loss: 0.5884 - val_mae: 0.6489
Epoch 9/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms

In [28]:
# Evaluación del modelo 3

eval3 = E3.evaluate(X_test, y_test)

print(f'Valores de pérdida modelo 3: {eval3}')

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.2755 - mae: 0.4203 
Valores de pérdida modelo 3: [0.27483677864074707, 0.41845667362213135]


#### Experiment 4: Add a Batch Normalization Layer after each Dropout Layer

In [19]:
# Experiment 4: a single dense hidden layer

E4 = Sequential()

# Agregar capa de entrada con 64 unidades y activación Relu y dimensión de entrada = 7

E4.add(Dense(64, activation="relu", input_dim = 7))

# Agregar capa densa oculta 1 con 32 unidades y función de activación Relu

E4.add(Dense(32, activation="relu")) # dense hidden layer 1

# Agregar una capa de dropout después del dense hidden layer 1

E4.add(Dropout(0.5)) # dropout layer after dense hidden layer 1

# Agregar batch normalization layer después del dropout layer 1

E4.add(BatchNormalization()) # Batch Normalization Layer after Dropout Layer 1

# Agregar capa densa oculta 2 con 16 unidades y función de activación Relu

E4.add(Dense(16, activation="relu")) # dense hidden layer 2

# Agregar capa de dropout después del dense hidden layer 2

E4.add(Dropout(0.5)) # dropout layer after dense hidden layer 2

# Agregar batch normalization layer después del dropout layer 2

E4.add(BatchNormalization()) # Batch Normalization Layer after Dropout Layer 2

# Agregar capa densa oculta 3 con 8 unidades y función de activación Relu

E4.add(Dense(8, activation="relu")) # dense hidden layer 3

# Agregar capa de dropout después del dense hidden layer 3

E4.add(Dropout(0.5)) # dropout layer after dense hidden layer 3

# Agregar batch normalization layer después del dropout layer 3

E4.add(BatchNormalization()) # Batch Normalization Layer after Dropout Layer 3

# Añadir capa de salida con 1 unidad 

E4.add(Dense(1))

In [20]:
# Compilar el modelo 4 (con batchnormalization después de cada dropout layer)

E4.compile(optimizer="adam", loss="mse", metrics=["mae"])

In [21]:
# Entrenamiento del modelo 4

E4.fit(X_train, y_train, epochs=100, batch_size=10, validation_split=0.2)

Epoch 1/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4.9914 - mae: 1.9054 - val_loss: 2.9514 - val_mae: 1.5834
Epoch 2/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.7381 - mae: 1.3778 - val_loss: 1.5947 - val_mae: 1.1185
Epoch 3/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.6927 - mae: 1.0570 - val_loss: 0.6834 - val_mae: 0.7019
Epoch 4/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.2140 - mae: 0.8828 - val_loss: 0.5100 - val_mae: 0.6068
Epoch 5/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9923 - mae: 0.8036 - val_loss: 0.4442 - val_mae: 0.5673
Epoch 6/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9045 - mae: 0.7581 - val_loss: 0.4991 - val_mae: 0.6043
Epoch 7/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8158 - mae: 0.7293 - val_loss: 0.4318 - val_mae: 0.5564
Epoch 8/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7120 - mae: 0.6852 - val_loss: 0.4299 - val_mae: 0.5555
Epoch 9/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/

In [22]:
# Evaluación del modelo 4

eval4 = E4.evaluate(X_test, y_test)

print(f'Valores de pérdida modelo 4: {eval4}')

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.2264 - mae: 0.4028 
Valores de pérdida modelo 4: [0.24065794050693512, 0.4098511040210724]


### 8. Predictions with the 4 models

In [23]:
pred_model1 = E1.predict(X_test) # predictions with model 1 (single dense layer)

pred_model2 = E2.predict(X_test) # predictions with model 2 (3 dense hidden layers)

pred_model3 = E3.predict(X_test) # predictions with model 3 (3 Dense hidden layers + dropout)

pred_model4 = E4.predict(X_test) # predictions with model 4 (Dense hidden layers + dropout + batch normalization)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step


### 9. Tabla comparativa de valores reales de GPA contra predicciones de los 4 modelos

In [24]:
pred_model1 = pd.Series(np.reshape(pred_model1, len(pred_model1)))
pred_model1.index = y_test.index

pred_model2 = pd.Series(np.reshape(pred_model2, len(pred_model2)))
pred_model2.index = y_test.index

pred_model3 = pd.Series(np.reshape(pred_model3, len(pred_model3)))
pred_model3.index = y_test.index

pred_model4 = pd.Series(np.reshape(pred_model4, len(pred_model4)))
pred_model4.index = y_test.index

In [25]:
GPA_realvspred = pd.DataFrame({"Modelo 1": pd.Series(np.reshape(pred_model1, len(pred_model1))), 
                               "Modelo 2": pd.Series(np.reshape(pred_model2, len(pred_model2))), 
                               "Modelo 3": pd.Series(np.reshape(pred_model3, len(pred_model3))), 
                               "Modelo 4": pd.Series(np.reshape(pred_model4, len(pred_model4))), 
                               "GPA real": y_test})

GPA_realvspred

Modelo 1  Modelo 2  Modelo 3  Modelo 4  GPA real
1004  1.362935  1.535858  1.487540  1.663879  1.427724
196   3.048964  3.150845  2.423644  2.798783  3.117354
2342  2.081095  2.187081  1.970699  1.885336  2.037769
1708  3.716757  3.860939  2.666003  4.180348  3.548521
435   0.451198  0.494626  1.243160  1.042828  0.248977
...        ...       ...       ...       ...       ...
986   1.853950  1.775873  1.997903  1.894092  1.562360
120   2.074698  2.103497  2.024846  1.915603  2.174903
283   2.169771  2.261521  2.133455  1.925295  2.332540
1740  2.725360  2.729002  2.193378  1.917401  2.777967
1726  0.986181  0.859922  1.364492  1.509829  0.863545

[479 rows x 5 columns]

### 10. Tabla comparativa de métricas (MSE y MAE) de los 4 modelos

In [27]:
metrics_table = pd.DataFrame({"MSE": [0.0587,0.0534,0.2755,0.2264], 
                              "MAE":[0.1782,0.1711,0.4203,0.4028]}, 
                              index=["Single Dense Hidden Layer", "3 Dense Hidden Layers", "Dense + Dropout", "Dense + Dropout + Batch Normalization"])

# Asignar nombre al índice del dataframe anterior

metrics_table.index.name = "Modelo"

# Mostrar los valores de las métricas para los 4 modelos: valores de pérdida MSE Y MAE

metrics_table

MSE     MAE
Modelo                                               
Single Dense Hidden Layer              0.0587  0.1782
3 Dense Hidden Layers                  0.0534  0.1711
Dense + Dropout                        0.2755  0.4203
Dense + Dropout + Batch Normalization  0.2264  0.4028

### 11. Conclusión final sobre el mejor modelo

En conclusión, es posible afirmar que de los 4 modelos probados anteriormente, aquel que resulta tener el mejor desempeño es el modelo 2 (aquel con 3 capas densas ocultas) y sin dropout ni batch normalization, esto principalmente debido a que éste modelo posee un valor de MSE igual a 0.0534 junto con un MAE de 0.1711, siendo éstos los menores valores posibles de MSE y MAE, de entre todos los modelos probados, lo cual es un indicativo de que el modelo con 3 capas densas ocultas (modelo 2) es aquel que arroja las predicciones con el mayor grado de precisión y confiabilidad posibles, mientras que los demás modelos, entre ellos, a los que se les aplicó batch normalization y dropout muestran tener una mayor margen de error en cuanto a su capacidad predictiva, esto principalmente porque poseen un mayor valor de MSE y de MAE que el modelo con triple capa densa oculta (3 Dense Hidden Layers), además, cabe mencionar que los modelos con el dropout y batch normalization aplicados es probable que tengan un mayor valor de MSE y MAE, debido a que el dataset de prueba para los modelos no contiene un volumen suficientemente alto de datos como para que las técnicas de dropout y batch normalization produzcan una mejoría significativa en la precisión de las predicciones de los modelos, además de que el hecho de utilizar alguna de éstas 2 técnicas, tales como el dropout, ocasiona por el contrario, que el MSE y el MAE de los modelos incremente, indicando mayor margen de error en las predicciones derivadas de los mismos, por lo que al tener una cantidad relativamente baja de datos en el dataset de prueba y aplicar técnicas como dropout y batch normalization, al momento de eliminar aleatoriamente ciertas neuronas de las redes, las predicciones de los modelos se sesgan más y por tanto pierden precisión y en consecuencia también su confiabilidad resulta ser menor, por lo que es más recomendable utilizar las técnicas de batch normalization y dropout en modelos que se pongan a prueba con una cantidad mayormente alta de datos en el dataset de prueba, esto para asegurar que al quitar neuronas de forma aleatoria mediante dropout, o bien, al aplicar batch normalization a los modelos en un intento por mejorar el desempeño de los mismos, éstos mismos modelos presenten una mejoría significativa en cuanto a su rendimiento predictivo, lo cual se traducirá en predicciones más precisas y confiables y en una mayor cantidad existente de alternativas para lograrlas, puesto que el dropout permitirá a los modelos explorar alternativas que probablemente no hayan sido exploradas anteriormente y que una de ellas sea la que arroje las predicciones más precisas y confiables posible de entre todas las posibilidades, además de que al haber muchos más datos, el quitar neuronas de los modelos tendrá un menor impacto negativo en en la precisión del mismo para realizar predicciones, por lo que las métricas como el MSE y el MAE ya no aumentarán significativamente al emplear tanto dropout como batch normalization. 